[general]
import = [
"~/.config/alacritty/themes/dracula.toml"
]

live_config_reload = true

[window]
dimensions = { columns = 113, lines = 28 }
position = { x = 150, y = 80 }
decorations = "None"
opacity = 0.80

[font]
size = 12
